name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Allure
        run: |
          npm install -g allure-commandline --save-dev

      - name: Run Cypress tests with Allure
        run: npx cypress run
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to Github Pages
        if: always()
        run: |
          git config --global user.name "RobertoFilho0100"
          git config --global user.email "robertocorreiafilho0100@gmail.com"
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          find allure-report -type f -exec cp {} ./ \;
          ls -l
          git add .
          git commit -m "Update Allure report" || echo "No changes to commit"
           git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/RobertoFilho0100/automacao-frontend-softcomshop.git gh-pages --force

      - name: Send Success Message to Discord
        if: ${{ success() }}
        run: |
          REPORT_TIME=$(TZ='America/Sao_Paulo' date "+%d/%m/%Y %H:%M:%S")
          REPORT_URL="https://robertofilho0100.github.io/automacao-frontend-softcomshop/allure-report/index.html"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
                "content": "✅ Todos os testes passaram com sucesso! 🎉\n\nVerifique o relatório em: '"$REPORT_URL"'",
                "embeds": [{
                  "title": "Allure Test Report",
                  "description": "A execução dos testes foi concluída com sucesso! :tada:",
                  "color": 3066993,
                  "fields": [{
                    "name": ":calendar: Data de Execução",
                    "value": "'"$REPORT_TIME"'"
                  }]
                }]
              }'

      - name: Send Failure Message to Discord
        if: ${{ failure() }}
        run: |
          REPORT_TIME=$(TZ='America/Sao_Paulo' date "+%d/%m/%Y %H:%M:%S")
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
                "content": "❌ Houveram falhas durante a execução dos testes. 👀\n\nVerifique o relatório em: '"$REPORT_URL"'",
                "embeds": [{
                  "title": "Allure Test Report",
                  "description": "Por favor, verifique o relatório para detalhes sobre as falhas. :warning:",
                  "color": 15158332,
                  "fields": [{
                    "name": ":calendar: Data de Execução",
                    "value": "'"$REPORT_TIME"'"
                  }]
                }]
              }'
